package tela.Usuario;

import controller.UsuarioController;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import model.Usuario;
import tela.util.Formatacao;
import tela.util.UsuarioLogadoBean;
import tela.FrmPrincipal;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wolverine
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private UsuarioLogadoBean usuarioLogadoBean;
    private int contador;

    /**
     * Creates new form FrmLoginD
     */
    public FrmLogin() {
        contador=0;
        this.usuarioLogadoBean = new tela.util.UsuarioLogadoBean();
        initComponents();
        URL url = this.getClass().getResource("/imagens/logoRelatorio/iconetela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
       try{
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);  
            this.pack();  
        }catch (Exception e){
        }
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginjPanel = new javax.swing.JPanel();
        senhajPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        loginjButton = new javax.swing.JButton();
        sairjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        loginjTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SysFIN - Login");

        loginjPanel.setBackground(new java.awt.Color(234, 238, 235));
        loginjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        senhajPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhajPasswordFieldActionPerformed(evt);
            }
        });
        loginjPanel.add(senhajPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, -1));

        jLabel1.setText("Senha de Acesso");
        loginjPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginjButton.setBackground(new java.awt.Color(204, 204, 204));
        loginjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/confirmar.png"))); // NOI18N
        loginjButton.setText("Confirmar");
        loginjButton.setToolTipText("Confirma entrada no sistema");
        loginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButtonActionPerformed(evt);
            }
        });
        jPanel3.add(loginjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 120, -1));

        sairjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/cancel.png"))); // NOI18N
        sairjButton.setText("Fechar");
        sairjButton.setToolTipText("Sair do Sistema");
        sairjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairjButtonfecharMovimentoCaixa(evt);
            }
        });
        jPanel3.add(sairjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 6, 100, -1));

        loginjPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 40));

        jLabel2.setText("Login do Usuário");
        loginjPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        loginjPanel.add(loginjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selecionar.png"))); // NOI18N
        jButton1.setText("Alterar");
        jButton1.setToolTipText("Alterar Senha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginjPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhajPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhajPasswordFieldActionPerformed
        loginjButtonActionPerformed(evt);
    }//GEN-LAST:event_senhajPasswordFieldActionPerformed

    private void loginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButtonActionPerformed
        UsuarioController usuarioController = new UsuarioController();
        Usuario usuario;
        String senha = "";
        if (senhajPasswordField.getPassword().length > 0) {
            senha = Formatacao.criptografarSenha(senhajPasswordField.getPassword());
            usuario = usuarioController.consultar(loginjTextField.getText(), senha);
            if (usuario == null) {
                JOptionPane.showMessageDialog(null, "Usuario e/ou Senha não conferem");
                verificarContagem();
            } else {
                usuarioLogadoBean.setUsuario(usuario);
                new FrmPrincipal(usuarioLogadoBean);
                this.dispose();
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Campo senha em branco");
        }
    }//GEN-LAST:event_loginjButtonActionPerformed

    private void sairjButtonfecharMovimentoCaixa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairjButtonfecharMovimentoCaixa
        System.exit(0);
    }//GEN-LAST:event_sairjButtonfecharMovimentoCaixa

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UsuarioController usuarioController = new UsuarioController();
        Usuario usuario;
        String senha = "";
        if (senhajPasswordField.getPassword().length > 0) {
            senha = Formatacao.criptografarSenha(senhajPasswordField.getPassword());
            usuario = usuarioController.consultar(loginjTextField.getText(), senha);
            if (usuario == null) {
                JOptionPane.showMessageDialog(null, "Usuario e/ou Senha não conferem");
                verificarContagem();
            } else {
                usuarioLogadoBean.setUsuario(usuario);
                new FrmAlterarSenha(usuarioLogadoBean.getUsuario());
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Campo senha em branco");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
        }catch (Exception e){
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginjButton;
    private javax.swing.JPanel loginjPanel;
    private javax.swing.JTextField loginjTextField;
    private javax.swing.JButton sairjButton;
    private javax.swing.JPasswordField senhajPasswordField;
    // End of variables declaration//GEN-END:variables

    public void verificarContagem(){
        if (contador>4){
            JOptionPane.showMessageDialog(rootPane, "Excedeu numero de tentativas");
            System.exit(0);
        }else {
            contador++;
            loginjTextField.setText("");
            senhajPasswordField.setText("");
            loginjTextField.requestFocus();
        }
    }

}
