/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela.Vendas;


import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Formapagamento;
import tela.ContasPagar.FrmCadastarContasPagar;
import tela.ContasPagar.FrmCarregarArquivo;
import tela.util.Formatacao;

/**
 *
 * @author Wolverine
 */
public class FrmLancarFormaPagamento extends javax.swing.JFrame implements IVendas{
    
   
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Formapagamento formaPagamento;
    private IVendas telaVendas;

    /**
     * Creates new form FrmLancarFormaPagamento
     */
    public FrmLancarFormaPagamento(String nomeCliente, String valorParcela, IVendas telaVendas) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/####";
        placeHolder = '_';
        this.telaVendas = telaVendas;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logoRelatorio/iconetela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        formaPagamento = new Formapagamento();
        nomejTextField.setText(nomeCliente);
        valorjTextField.setText(valorParcela);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public FrmLancarFormaPagamento(Formapagamento forma) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/####";
        placeHolder = '_';
        initComponents();
        confirmajButton.setEnabled(true);
        this.setLocationRelativeTo(null);
        visualizarFormaPagamento(forma);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tipoDocumentojComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cpfjTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tipoLogradourojComboBox = new javax.swing.JComboBox();
        logradourojTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        numerojTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        complementojTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bairrojTextField = new javax.swing.JTextField();
        cepjFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        cidadejTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        estadojComboBox = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numeroParcelasjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dataVencimentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel6 = new javax.swing.JLabel();
    valorjTextField = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    observacaojTextArea = new javax.swing.JTextArea();
    jLabel8 = new javax.swing.JLabel();
    arquivojTextField = new javax.swing.JTextField();
    carregarArquivojButton = new javax.swing.JButton();
    valorParcelajTextField = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    confirmajButton = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Lança Forma de Pagamento");

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel1.setText("Nome");

    nomejTextField.setEnabled(false);

    jLabel2.setText("Tipo de Documento");

    tipoDocumentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cheque", "Dinheiro", "Boleto", "Cartão", "Debito em Conta", "Depósito" }));
    tipoDocumentojComboBox.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            tipoDocumentojComboBoxItemStateChanged(evt);
        }
    });

    jLabel3.setText("Nº CPF/CNPJ");

    cpfjTextField.setEnabled(false);
    cpfjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            cpfjTextFieldKeyTyped(evt);
        }
    });

    jLabel13.setText("Tipo Logradouro");

    tipoLogradourojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Avenida", "BR", "Estrada", "Rodovia", "Rua", "Servidão", "Parque", "Travessa", " " }));
    tipoLogradourojComboBox.setEnabled(false);

    logradourojTextField.setEnabled(false);

    jLabel14.setText("Logradouro");

    numerojTextField.setEnabled(false);

    jLabel15.setText("Número");

    complementojTextField.setEnabled(false);

    jLabel16.setText("Complemento");

    jLabel17.setText("Bairro");

    bairrojTextField.setEnabled(false);

    cepjFormattedTextField.setEnabled(false);

    jLabel18.setText("CEP");

    cidadejTextField.setEnabled(false);

    jLabel19.setText("Cidade");

    estadojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
    estadojComboBox.setEnabled(false);

    jLabel21.setText("Estado");

    jLabel4.setText("No. Parcelas");

    numeroParcelasjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            numeroParcelasjTextFieldFocusLost(evt);
        }
    });
    numeroParcelasjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            numeroParcelasjTextFieldKeyTyped(evt);
        }
    });

    jLabel5.setText("Data Vencimento");

    dataVencimentojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataVencimentojDateChooserdataIniciojDateChooserFocusGained(evt);
        }
    });

    jLabel6.setText("Valor R$");

    valorjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            valorjTextFieldFocusLost(evt);
        }
    });
    valorjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            valorjTextFieldKeyTyped(evt);
        }
    });

    jLabel7.setText("Observação");

    observacaojTextArea.setColumns(20);
    observacaojTextArea.setRows(5);
    jScrollPane1.setViewportView(observacaojTextArea);

    jLabel8.setText("Nome do Arquivo");

    arquivojTextField.setEditable(false);

    carregarArquivojButton.setText("Carregar");
    carregarArquivojButton.setEnabled(false);
    carregarArquivojButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            carregarArquivojButtonActionPerformed(evt);
        }
    });

    valorParcelajTextField.setEditable(false);
    valorParcelajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    jLabel9.setText("Valor da Parcela");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(arquivojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(carregarArquivojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipoDocumentojComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tipoLogradourojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(logradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(numeroParcelasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(dataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(183, 183, 183))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(186, 186, 186))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(valorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cidadejTextField))
                                        .addGap(26, 26, 26)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(estadojComboBox, 0, 102, Short.MAX_VALUE)
                            .addComponent(jLabel21)
                            .addComponent(valorParcelajTextField)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
            .addContainerGap(20, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cpfjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tipoDocumentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipoLogradourojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logradourojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numerojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel21)
                        .addComponent(jLabel19)
                        .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numeroParcelasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valorParcelajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(arquivojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(carregarArquivojButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    confirmajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/confirmar.png"))); // NOI18N
    confirmajButton.setText("Confirmar");
    confirmajButton.setToolTipText("Confirmar");
    confirmajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            confirmajButtonActionPerformed(evt);
        }
    });

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/cancel.png"))); // NOI18N
    jButton5.setText("Cancelar");
    jButton5.setToolTipText("Cancelar");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(confirmajButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
            .addComponent(jButton5)
            .addGap(34, 34, 34))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(confirmajButton)
                .addComponent(jButton5))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(17, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataVencimentojDateChooserdataIniciojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataVencimentojDateChooserdataIniciojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataVencimentojDateChooserdataIniciojDateChooserFocusGained

    private void confirmajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmajButtonActionPerformed
        formaPagamento.setNomeCliente(nomejTextField.getText());
        formaPagamento.setTipoDocumento(tipoDocumentojComboBox.getSelectedItem().toString());
        formaPagamento.setLogradouro(logradourojTextField.getText());
        formaPagamento.setTipoLogradouro(tipoLogradourojComboBox.getSelectedItem().toString());
        formaPagamento.setNumero(numerojTextField.getText());
        formaPagamento.setComplemento(complementojTextField.getText());
        formaPagamento.setCep(cepjFormattedTextField.getText());
        formaPagamento.setBairro(bairrojTextField.getText());
        formaPagamento.setParcelaGerada("Não");
        formaPagamento.setCidade(cidadejTextField.getText());
        formaPagamento.setEstado(estadojComboBox.getSelectedItem().toString());
        formaPagamento.setCpf(cpfjTextField.getText());
        formaPagamento.setObservacao(observacaojTextArea.getText());
        if (numeroParcelasjTextField.getText().length()>0){
            formaPagamento.setNumeroParcelas(Integer.parseInt(numeroParcelasjTextField.getText()));
        }else formaPagamento.setNumeroParcelas(0);
        if (dataVencimentojDateChooser.getDate()!=null){
            formaPagamento.setDataVencimento(dataVencimentojDateChooser.getDate());
        }
        if (valorjTextField.getText().length()>0){
            formaPagamento.setValor(Formatacao.formatarStringfloat(valorjTextField.getText()));
        }else formaPagamento.setValor(0.0f);
        if (valorParcelajTextField.getText().length()>0){
            formaPagamento.setValorParcela(Formatacao.formatarStringfloat(valorParcelajTextField.getText()));
        }else formaPagamento.setValorParcela(0.0f);
        this.telaVendas.setFormaPagamento(formaPagamento);
        this.dispose();
    }//GEN-LAST:event_confirmajButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void numeroParcelasjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroParcelasjTextFieldFocusLost
        int numeroParcelas =0;
        if (numeroParcelasjTextField.getText().length()>0){
            numeroParcelas = Integer.parseInt(numeroParcelasjTextField.getText());
        }
        if (numeroParcelas>0){
            Float valor = 0.0f;
            if (valorjTextField.getText().length()>0){
                valor = Formatacao.formatarStringfloat(valorjTextField.getText());
                if (valor>0){
                    valorParcelajTextField.setText(Formatacao.foramtarFloatString((valor/numeroParcelas)));
                }
            }
        }
    }//GEN-LAST:event_numeroParcelasjTextFieldFocusLost

    private void valorjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorjTextFieldFocusLost
        int numeroParcelas =0;
        if (numeroParcelasjTextField.getText().length()>0){
            numeroParcelas = Integer.parseInt(numeroParcelasjTextField.getText());
        }
        if (numeroParcelas>0){
            Float valor = 0.0f;
            if (valorjTextField.getText().length()>0){
                valor = Formatacao.formatarStringfloat(valorjTextField.getText());
                if (valor>0){
                    valorParcelajTextField.setText(Formatacao.foramtarFloatString((valor/numeroParcelas)));
                }
            }
        }
    }//GEN-LAST:event_valorjTextFieldFocusLost

    private void numeroParcelasjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroParcelasjTextFieldKeyTyped
        String caracteres = "0987654321";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_numeroParcelasjTextFieldKeyTyped

    private void valorjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorjTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_valorjTextFieldKeyTyped

    private void cpfjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfjTextFieldKeyTyped
        if (evt.getKeyChar()==','){
            evt.setKeyChar('.');
        }
        String caracteres = "0987654321.-/";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_cpfjTextFieldKeyTyped

    private void carregarArquivojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarArquivojButtonActionPerformed
        new FrmCarregarArquivo(this);
    }//GEN-LAST:event_carregarArquivojButtonActionPerformed

    private void tipoDocumentojComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoDocumentojComboBoxItemStateChanged
        String item = tipoDocumentojComboBox.getSelectedItem().toString();
        if (item.equalsIgnoreCase("Boleto")){
            tipoLogradourojComboBox.setEnabled(true);
            logradourojTextField.setEnabled(true);
            numerojTextField.setEnabled(true);
            complementojTextField.setEnabled(true);
            bairrojTextField.setEnabled(true);
            cepjFormattedTextField.setEnabled(true);
            cidadejTextField.setEnabled(true);
            estadojComboBox.setEnabled(true);
            cpfjTextField.setEnabled(true);
        }else {
            tipoLogradourojComboBox.setEnabled(false);
            logradourojTextField.setEnabled(false);
            numerojTextField.setEnabled(false);
            complementojTextField.setEnabled(false);
            bairrojTextField.setEnabled(false);
            cepjFormattedTextField.setEnabled(false);
            cidadejTextField.setEnabled(false);
            estadojComboBox.setEnabled(false);
            cpfjTextField.setEnabled(false);
        }
        if (item.equalsIgnoreCase("Cartão")){
            carregarArquivojButton.setEnabled(true);
        }else {
            if (item.equalsIgnoreCase("Depósito")){
                carregarArquivojButton.setEnabled(true);
            }else {
                carregarArquivojButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tipoDocumentojComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arquivojTextField;
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JButton carregarArquivojButton;
    private javax.swing.JFormattedTextField cepjFormattedTextField;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JTextField complementojTextField;
    private javax.swing.JButton confirmajButton;
    private javax.swing.JTextField cpfjTextField;
    private com.toedter.calendar.JDateChooser dataVencimentojDateChooser;
    private javax.swing.JComboBox estadojComboBox;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField logradourojTextField;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField numeroParcelasjTextField;
    private javax.swing.JTextField numerojTextField;
    private javax.swing.JTextArea observacaojTextArea;
    private javax.swing.JComboBox tipoDocumentojComboBox;
    private javax.swing.JComboBox tipoLogradourojComboBox;
    private javax.swing.JTextField valorParcelajTextField;
    private javax.swing.JTextField valorjTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setCliente(Cliente cliente) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void setArquivo(File arquivo) {
        if (arquivo!=null){
            arquivojTextField.setText(arquivo.getAbsolutePath() + " " + arquivo.getName());
            try {
                this.formaPagamento.setComprovante(gerarArquivoBase(arquivo));
            } catch (IOException ex) {
                Logger.getLogger(FrmCadastarContasPagar.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Erro Carregar Arquivo " + ex);
            }
        }
    }
    
    public byte[] gerarArquivoBase(File file) throws IOException {
        InputStream is = new FileInputStream(file);
        byte[] xml = new byte[(int) file.length()];
        int offset = 0;
        int numRead = 0;
        while (offset < xml.length
                && (numRead = is.read(xml, offset, xml.length - offset)) >= 0) {
            offset += numRead;
        }
        return xml;
    }

    @Override
    public void setFormaPagamento(Formapagamento formaPagamento) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void visualizarFormaPagamento(Formapagamento forma){
        tipoDocumentojComboBox.setEnabled(false);
        tipoDocumentojComboBox.setSelectedItem(forma.getTipoDocumento());
        nomejTextField.setText(forma.getNomeCliente());
        cpfjTextField.setText(forma.getCpf());
        if (forma.getTipoDocumento().equalsIgnoreCase("Boleto")){
            tipoLogradourojComboBox.setSelectedItem(forma.getTipoLogradouro());
            logradourojTextField.setText(forma.getLogradouro());
            numerojTextField.setText(forma.getNumero());
            complementojTextField.setText(forma.getComplemento());
            bairrojTextField.setText(forma.getBairro());
            cidadejTextField.setText(forma.getCidade());
            estadojComboBox.setSelectedItem(forma.getEstado());
            cepjFormattedTextField.setText(forma.getCep());
        }
        numeroParcelasjTextField.setText(String.valueOf(forma.getNumeroParcelas()));
        numeroParcelasjTextField.setEnabled(false);
        dataVencimentojDateChooser.setDate(forma.getDataVencimento());
        dataVencimentojDateChooser.setEnabled(false);
        valorjTextField.setText(Formatacao.foramtarFloatString(forma.getValor()));
        valorjTextField.setEnabled(false);
        valorParcelajTextField.setText(Formatacao.foramtarFloatString(forma.getValorParcela()));
        valorParcelajTextField.setEnabled(false);
        observacaojTextArea.setText(forma.getObservacao());
        observacaojTextArea.setEnabled(false);
    }

    @Override
    public void exportarExcel(String caminho, String nomeArquivo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void pesquisar(String sql) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
