/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela.Vendas;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.BancoController;
import controller.ClienteController;
import controller.ContasReceberController;
import controller.FormaPagamentoController;
import controller.PlanoContasController;
import controller.VendasController;
import java.awt.Image;
import java.awt.Toolkit;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.Banco;
import model.Cliente;
import model.Contasreceber;
import model.Formapagamento;
import model.Planocontas;
import model.Vendas;
import modelView.Viewvendas;
import tela.util.Formatacao;
import tela.util.UsuarioLogadoBean;

/**
 *
 * @author Wolverine
 */
public class FrmLancarContasReceber extends javax.swing.JFrame implements IVendas{
    
    private Viewvendas vendas;
    private List<ParcelasBean> listaParcelas;
    private UsuarioLogadoBean usuarioLogadoBean;
    private parcelasTableModel modelParcela;
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private int linha=-1;
    private IVendas telaVendas;

    /**
     * Creates new form FrmLancarContasReceber
     */
    public FrmLancarContasReceber(UsuarioLogadoBean usuarioLogadoBean, Viewvendas vendas, IVendas telaVendas) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/####";
        placeHolder = '_';
        this.telaVendas = telaVendas;
        this.usuarioLogadoBean = usuarioLogadoBean;
        this.vendas = vendas;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logoRelatorio/iconetela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        inicializarParcelas();
        this.setLocationRelativeTo(null);
        parcelasjTable.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);  
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        valorBrutojTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numeroParcelasjComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataVencimentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jButton1 = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    tipojComboBox = new javax.swing.JComboBox();
    clientejTextField = new javax.swing.JTextField();
    jButton2 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    parcelasjTable = new javax.swing.JTable();
    jLabel7 = new javax.swing.JLabel();
    adocumentojTextField = new javax.swing.JTextField();
    adataVencimentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
aValorParcelajTextField = new javax.swing.JTextField();
jLabel8 = new javax.swing.JLabel();
jLabel9 = new javax.swing.JLabel();
jPanel3 = new javax.swing.JPanel();
alterarjButton = new javax.swing.JButton();
confirmarjButton = new javax.swing.JButton();
cancelarjButton = new javax.swing.JButton();
tipoAlterarjComboBox = new javax.swing.JComboBox();
jLabel6 = new javax.swing.JLabel();
jPanel4 = new javax.swing.JPanel();
jButton3 = new javax.swing.JButton();
registarjButton = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Gerar Parcelas");

jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel1.setText("Valor Total :");

valorBrutojTextField.setEditable(false);
valorBrutojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
valorBrutojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyTyped(java.awt.event.KeyEvent evt) {
        valorBrutojTextFieldKeyTyped(evt);
    }
    });

    jLabel2.setText("Número Parcelas :");

    numeroParcelasjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

    jLabel3.setText("Cliente :");

    jLabel4.setText("Data 1o. Vencimento :");

    dataVencimentojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataVencimentojDateChooserFocusGained(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/enviar.png"))); // NOI18N
    jButton1.setText("Gerar Parcelas");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jLabel5.setText("Tipo Documento :");

    tipojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cheque", "Dinheiro", "Boleto", "Cartão", "Debito em Conta", "Depósito" }));

    clientejTextField.setEditable(false);

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selecionar.png"))); // NOI18N
    jButton2.setText("Selecionar Forma");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(numeroParcelasjComboBox, 0, 135, Short.MAX_VALUE)
                        .addComponent(valorBrutojTextField))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dataVencimentojDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tipojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(clientejTextField))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(clientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(valorBrutojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addComponent(dataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(numeroParcelasjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    parcelasjTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "No. Documento", "Data Lançamento", "Parcela", "Data Vencimento", "Valor da Parcela", "Tipo Documento"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    parcelasjTable.setDropMode(javax.swing.DropMode.ON);
    parcelasjTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            parcelasjTableMouseClicked(evt);
        }
    });
    parcelasjTable.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            parcelasjTableKeyPressed(evt);
        }
    });
    jScrollPane1.setViewportView(parcelasjTable);
    if (parcelasjTable.getColumnModel().getColumnCount() > 0) {
        parcelasjTable.getColumnModel().getColumn(0).setResizable(false);
        parcelasjTable.getColumnModel().getColumn(1).setResizable(false);
        parcelasjTable.getColumnModel().getColumn(2).setResizable(false);
        parcelasjTable.getColumnModel().getColumn(3).setResizable(false);
        parcelasjTable.getColumnModel().getColumn(4).setResizable(false);
        parcelasjTable.getColumnModel().getColumn(5).setResizable(false);
    }

    jLabel7.setText("No. Documento");

    adataVencimentojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            adataVencimentojDateChooserFocusGained(evt);
        }
    });

    aValorParcelajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    jLabel8.setText("Data Vencimento");

    jLabel9.setText("Valor da Parcela");

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    alterarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/anexar.png"))); // NOI18N
    alterarjButton.setText("Alterar");
    alterarjButton.setToolTipText("Alterar Parcela");
    alterarjButton.setEnabled(false);
    alterarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            alterarjButtonActionPerformed(evt);
        }
    });

    confirmarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/confirmar.png"))); // NOI18N
    confirmarjButton.setText("Confirmar");
    confirmarjButton.setToolTipText("Confirma alteração da parcela");
    confirmarjButton.setEnabled(false);
    confirmarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            confirmarjButtonActionPerformed(evt);
        }
    });

    cancelarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/cancel.png"))); // NOI18N
    cancelarjButton.setText("Cancelar");
    cancelarjButton.setToolTipText("Cancela alteração da parcela");
    cancelarjButton.setEnabled(false);
    cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelarjButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(alterarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)
            .addComponent(confirmarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cancelarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addGap(7, 7, 7))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(alterarjButton)
                .addComponent(confirmarjButton)
                .addComponent(cancelarjButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    tipoAlterarjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cheque", "Dinheiro", "Boleto", "Cartão", "Debito em Conta", "Depósito" }));

    jLabel6.setText("Tipo Documento");

    jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/enviar.png"))); // NOI18N
    jButton3.setText("Sem Parcelas");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    registarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/confirmar.png"))); // NOI18N
    registarjButton.setText("Registrar");
    registarjButton.setEnabled(false);
    registarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            registarjButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(29, 29, 29)
            .addComponent(registarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton3)
                .addComponent(registarjButton))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(adocumentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(41, 41, 41)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(adataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(aValorParcelajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(tipoAlterarjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(16, 16, 16))))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(181, 181, 181)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(adocumentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(adataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tipoAlterarjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aValorParcelajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(23, 23, 23))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataVencimentojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataVencimentojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataVencimentojDateChooserFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerarParcelas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void parcelasjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parcelasjTableMouseClicked
        int linha = parcelasjTable.getSelectedRow();
        if (linha>=0){
            alterarjButton.setEnabled(true);
        }
    }//GEN-LAST:event_parcelasjTableMouseClicked

    private void parcelasjTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parcelasjTableKeyPressed
        if (evt.getKeyCode()==VK_ENTER){
            int coluna = parcelasjTable.getSelectedColumn();
            int linha = parcelasjTable.getSelectedRow();
            if (coluna==0){
                listaParcelas.get(linha).setNumeroDocumento(datePattern);
            }
        }
    }//GEN-LAST:event_parcelasjTableKeyPressed

    private void valorBrutojTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorBrutojTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_valorBrutojTextFieldKeyTyped

    private void registarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarjButtonActionPerformed
        BancoController bancoController = new BancoController();
        Banco banco  = bancoController.consultar(vendas.getClienteIdcliente(), " Nenhum");
        ClienteController clienteController = new ClienteController();
        Cliente cliente = clienteController.consultar(vendas.getClienteIdcliente());
        for(int i=0;i<listaParcelas.size();i++){
            ParcelasBean parcela = listaParcelas.get(i);
            Contasreceber conta = new Contasreceber();
            conta.setBanco(banco);
            conta.setCliente(cliente);
            conta.setDataVencimento(parcela.getDataVenciemnto());
            conta.setDesagio(0.0f);
            conta.setTipodocumento(parcela.getTipoDocumento());
            conta.setJuros(0.0f);
            conta.setValorPago(0.0f);
            conta.setMovimentoBanco(0);
            conta.setNomeCliente(vendas.getNomeCliente());
            conta.setNumeroDocumento(parcela.getNumeroDocumento());
            conta.setNumeroParcela(parcela.getNumeroParcela());
            conta.setUsuario(usuarioLogadoBean.getUsuario());
            conta.setValorParcela(parcela.getValorParcelas());
            PlanoContasController planoContasController = new PlanoContasController();
            Planocontas plano = planoContasController.consultar(cliente.getContaRecebimento());
            conta.setPlanocontas(plano);
            conta.setVenda(vendas.getIdvendas());
            ContasReceberController contasReceberController = new ContasReceberController();
            conta = contasReceberController.salvar(conta);
        }
        VendasController vendasController = new VendasController();
        Vendas venda = vendasController.consultar(vendas.getIdvendas());
        if (venda!=null){
            venda.setSituacao("verde");
            venda = vendasController.salvar(venda);
        }
        JOptionPane.showMessageDialog(rootPane, "Contas Registradas com Sucesso");
        this.telaVendas.setModel();
        this.dispose();
    }//GEN-LAST:event_registarjButtonActionPerformed

    private void adataVencimentojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adataVencimentojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_adataVencimentojDateChooserFocusGained

    private void alterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarjButtonActionPerformed
        linha= parcelasjTable.getSelectedRow();
        if (linha>=0){
            adocumentojTextField.setText(listaParcelas.get(linha).getNumeroDocumento());
            adataVencimentojDateChooser.setDate(listaParcelas.get(linha).getDataVenciemnto());
            aValorParcelajTextField.setText(Formatacao.foramtarFloatString(listaParcelas.get(linha).getValorParcelas()));
            alterarjButton.setEnabled(false);
            confirmarjButton.setEnabled(true);
            cancelarjButton.setEnabled(true);
            tipoAlterarjComboBox.setSelectedItem(listaParcelas.get(linha).getTipoDocumento());
        }
    }//GEN-LAST:event_alterarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        adocumentojTextField.setText("");
        adataVencimentojDateChooser.setDate(null);
        aValorParcelajTextField.setText("");
        confirmarjButton.setEnabled(false);
        cancelarjButton.setEnabled(false);
        alterarjButton.setEnabled(false);
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void confirmarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarjButtonActionPerformed
        if (linha >= 0) {
            listaParcelas.get(linha).setNumeroDocumento(adocumentojTextField.getText());
            listaParcelas.get(linha).setDataVenciemnto(adataVencimentojDateChooser.getDate());
            listaParcelas.get(linha).setValorParcelas(Formatacao.formatarStringfloat(aValorParcelajTextField.getText()));
            listaParcelas.get(linha).setTipoDocumento(tipoAlterarjComboBox.getSelectedItem().toString());
            calcularValores();
            modelParcela = new parcelasTableModel(listaParcelas);
            parcelasjTable.setModel(modelParcela);
            DefaultTableCellRenderer rendererValor = new DefaultTableCellRenderer();
            rendererValor.setHorizontalAlignment(SwingConstants.RIGHT);
            parcelasjTable.getColumnModel().getColumn(0).setCellEditor(new StandartTableCellEditor());
            parcelasjTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            parcelasjTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            parcelasjTable.getColumnModel().getColumn(2).setPreferredWidth(30);
            parcelasjTable.getColumnModel().getColumn(3).setCellEditor(new StandartTableCellEditor());
            parcelasjTable.getColumnModel().getColumn(3).setPreferredWidth(50);
            parcelasjTable.getColumnModel().getColumn(4).setCellEditor(new StandartTableCellEditor());
            parcelasjTable.getColumnModel().getColumn(4).setCellRenderer(rendererValor);
            parcelasjTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            parcelasjTable.repaint();
            registarjButton.setEnabled(true);
             adocumentojTextField.setText("");
            adataVencimentojDateChooser.setDate(null);
            aValorParcelajTextField.setText("");
            confirmarjButton.setEnabled(false);
            cancelarjButton.setEnabled(false);
            alterarjButton.setEnabled(false);
        }
    }//GEN-LAST:event_confirmarjButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new FrmConsultarFormaPagamento(vendas.getIdvendas(), this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean resultado = JOptionPane.showConfirmDialog(null, "Confirma Lançamento SEM PARCELAS?", "Excluir", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0;
        if (resultado) {
            VendasController vendasController = new VendasController();
            Vendas venda = vendasController.consultar(vendas.getIdvendas());
            if (venda != null) {
                venda.setSituacao("verde");
                vendasController.salvar(venda);
                telaVendas.setModel();
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aValorParcelajTextField;
    private com.toedter.calendar.JDateChooser adataVencimentojDateChooser;
    private javax.swing.JTextField adocumentojTextField;
    private javax.swing.JButton alterarjButton;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JTextField clientejTextField;
    private javax.swing.JButton confirmarjButton;
    private com.toedter.calendar.JDateChooser dataVencimentojDateChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox numeroParcelasjComboBox;
    private javax.swing.JTable parcelasjTable;
    private javax.swing.JButton registarjButton;
    private javax.swing.JComboBox tipoAlterarjComboBox;
    private javax.swing.JComboBox tipojComboBox;
    private javax.swing.JTextField valorBrutojTextField;
    // End of variables declaration//GEN-END:variables

    private void inicializarParcelas(){
        clientejTextField.setText(vendas.getNomeCliente());
        valorBrutojTextField.setText(Formatacao.foramtarFloatString(vendas.getValorLiquido()-vendas.getValorPagoFornecedor()));
        dataVencimentojDateChooser.setDate(new Date());
    }
    
    public void gerarParcelas(){
        String data = Formatacao.ConvercaoDataPadrao(dataVencimentojDateChooser.getDate());
        String mes = data.substring(3, 5);
        String ano = data.substring(6, 10);
        String dia = data.substring(0,2);
        int cmes = Integer.parseInt(mes);
        int cano = Integer.parseInt(ano);
        int numeroParcelas = Integer.parseInt(numeroParcelasjComboBox.getSelectedItem().toString());
        Float valorParcela = (vendas.getValorLiquido() - vendas.getValorPagoFornecedor());
        valorParcela = (valorParcela/numeroParcelas);
        listaParcelas = new ArrayList<ParcelasBean>();
        Date cData = dataVencimentojDateChooser.getDate();
        for(int i=0;i<numeroParcelas;i++){
            ParcelasBean parcela = new ParcelasBean();
            parcela.setDataLancamento(new Date());
            parcela.setNumeroDocumento(String.valueOf(vendas.getIdvendas()));
            parcela.setNumeroParcela(i+1);
            parcela.setValorParcelas(valorParcela);
            parcela.setDataVenciemnto(cData);
            parcela.setTipoDocumento(tipojComboBox.getSelectedItem().toString());
            listaParcelas.add(parcela);
            if (cmes==12){
                cmes = 1;
                cano = cano + 1;
            }else {
                cmes=cmes +1;
            }
            if (cmes<10){
                data = dia + "/" + "0" + String.valueOf(cmes) +  "/" + String.valueOf(cano);
            }else {
                data = dia + "/"  + String.valueOf(cmes) +  "/" + String.valueOf(cano);
            }
            cData = Formatacao.ConvercaoStringDataBrasil(data);
        }
        modelParcela = new parcelasTableModel(listaParcelas);
        parcelasjTable.setModel(modelParcela);
        DefaultTableCellRenderer rendererValor = new DefaultTableCellRenderer();
        rendererValor.setHorizontalAlignment(SwingConstants.RIGHT);
        parcelasjTable.getColumnModel().getColumn(0).setCellEditor(new StandartTableCellEditor());
        parcelasjTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        parcelasjTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        parcelasjTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        parcelasjTable.getColumnModel().getColumn(3).setCellEditor(new StandartTableCellEditor());
        parcelasjTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        parcelasjTable.getColumnModel().getColumn(4).setCellEditor(new StandartTableCellEditor());
        parcelasjTable.getColumnModel().getColumn(4).setCellRenderer(rendererValor);
        parcelasjTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        parcelasjTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        parcelasjTable.repaint();
        registarjButton.setEnabled(true);
    }
    
    public void calcularValores(){
        float valorTotal = Formatacao.formatarStringfloat(valorBrutojTextField.getText());
        float valorAlterado=0;
        for (int i=0;i<listaParcelas.size();i++){
            if (i<=linha){
                valorAlterado = valorAlterado + listaParcelas.get(i).getValorParcelas();
            }
        }
        float valor = valorTotal - valorAlterado;
        int numero = listaParcelas.size() - (linha+1);
        valor = valor / numero;
        for (int i=0;i<listaParcelas.size();i++){
            if (i>linha){
                listaParcelas.get(i).setValorParcelas(valor);
            }
        }
    }

    @Override
    public void setModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setCliente(Cliente cliente) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setArquivo(File arquivo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setFormaPagamento(Formapagamento formaPagamento) {
        if (formaPagamento!=null){
            valorBrutojTextField.setText(Formatacao.foramtarFloatString(formaPagamento.getValor()));
            String numero = String.valueOf(formaPagamento.getNumeroParcelas());
            if (formaPagamento.getNumeroParcelas()<10){
                numero = "0" + numero;
            }
            numeroParcelasjComboBox.setSelectedItem(numero);
            tipojComboBox.setSelectedItem(formaPagamento.getTipoDocumento());
            dataVencimentojDateChooser.setDate(formaPagamento.getDataVencimento());
            FormaPagamentoController formaPagamentoController =new FormaPagamentoController();
            formaPagamento.setParcelaGerada("SIM");
            formaPagamento = formaPagamentoController.salvar(formaPagamento);
        }
    }

    @Override
    public void exportarExcel(String caminho, String nomeArquivo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void pesquisar(String sql, String order) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setNumeroColuna(int numero) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
