/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela.Vendas;

import IntegracaoSysTM.IntegracaoController;
import IntegracaoSysTM.Orcamentoprodutosorcamento;
import IntegracaoSysTM.SParcelamentopagamento;
import IntegracaoSysTM.Viewvendasintegracao;
import com.toedter.calendar.JTextFieldDateEditor;
import controller.ClienteController;
import controller.FormaPagamentoController;
import controller.ProdutoController;
import controller.VendasController;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import model.Cliente;
import model.Emissaonota;
import model.Formapagamento;
import model.Produto;
import model.Vendas;
import model.Vendas_;
import tela.Cliente.FrmConsultaCliente;
import tela.util.Formatacao;
import tela.util.LimiteTextoJedit;
import tela.util.UsuarioLogadoBean;

/**
 *
 * @author Wolverine
 */
public class FrmLancarVenda extends javax.swing.JFrame implements IVendas{
    
    private UsuarioLogadoBean usuarioLogadoBean;
    private Vendas venda;
    private IVendas telaVednas;
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private Cliente cliente;
    private List<Formapagamento> listaForma;
    private ConsultaFormaPagamentoTableModel modelForma;
    
    /**
     * Creates new form FrmLancarVenda
     */
    public FrmLancarVenda(UsuarioLogadoBean usuarioLogadoBean, IVendas telaVenda, int idVenda) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/####";
        placeHolder = '_';
        this.usuarioLogadoBean = usuarioLogadoBean;
        this.telaVednas = telaVenda;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logoRelatorio/iconetela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        limitarJText();
        if (idVenda>0){
            inicilizarEditarVendas(idVenda);
        }else inicilizarNovaVendas();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        unidadejTextField = new javax.swing.JTextField();
        selecionarjButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        produtojComboBox = new javax.swing.JComboBox();
        dataVendajDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    totalBrutojTextField = new javax.swing.JTextField();
    jLabel16 = new javax.swing.JLabel();
    valorDescontojTextField = new javax.swing.JTextField();
    totalLiquidojTextField = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    clientejTextField = new javax.swing.JTextField();
    jLabel21 = new javax.swing.JLabel();
    consultorjTextField = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jLabel11 = new javax.swing.JLabel();
    comissaoLiquidajTextField = new javax.swing.JTextField();
    comissaoFuncionariojTextField = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    despesasFinanceirajTextField = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    jLabel25 = new javax.swing.JLabel();
    comissaoTerceirosjTextField = new javax.swing.JTextField();
    jLabel27 = new javax.swing.JLabel();
    dataPagamentoFornecedorjDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
totalVendajTextField = new javax.swing.JTextField();
jLabel26 = new javax.swing.JLabel();
jLabel28 = new javax.swing.JLabel();
valorPagoFornecedorjTextField = new javax.swing.JTextField();
valorReceberjLabel = new javax.swing.JLabel();
LiquidoVendaojTextField = new javax.swing.JTextField();
nomefornecedorjTextField = new javax.swing.JTextField();
jLabel2 = new javax.swing.JLabel();
jLabel30 = new javax.swing.JLabel();
pagarReceberjTextField = new javax.swing.JTextField();
jLabel22 = new javax.swing.JLabel();
observacoesjTextField = new javax.swing.JTextField();
jPanel1 = new javax.swing.JPanel();
jScrollPane1 = new javax.swing.JScrollPane();
formajTable = new javax.swing.JTable();
BarradeTarefasjToolBar = new javax.swing.JToolBar();
adicionarAPagarjButton = new javax.swing.JButton();
excluirAPagarjButton = new javax.swing.JButton();
jPanel3 = new javax.swing.JPanel();
jLabel1 = new javax.swing.JLabel();
nomejTextField = new javax.swing.JTextField();
jLabel3 = new javax.swing.JLabel();
enderecojTextField = new javax.swing.JTextField();
jLabel4 = new javax.swing.JLabel();
complementojTextField = new javax.swing.JTextField();
jLabel8 = new javax.swing.JLabel();
bairrojTextField = new javax.swing.JTextField();
jLabel9 = new javax.swing.JLabel();
cidadejTextField = new javax.swing.JTextField();
jLabel10 = new javax.swing.JLabel();
estadojComboBox = new javax.swing.JComboBox();
jLabel18 = new javax.swing.JLabel();
cepjFormattedTextField = new javax.swing.JFormattedTextField();
cnpjjTextField = new javax.swing.JTextField();
jLabel19 = new javax.swing.JLabel();
iejTextField = new javax.swing.JTextField();
jLabel20 = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Lancar Vendas");

jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/confirmar.png"))); // NOI18N
jButton1.setText("Confirmar");
jButton1.setToolTipText("Confirmar");
jButton1.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
    }
    });

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/cancel.png"))); // NOI18N
    jButton5.setText("Cancelar");
    jButton5.setToolTipText("Cancelar");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/anexar.png"))); // NOI18N
    jButton2.setText("Importar");
    jButton2.setToolTipText("Importar de Sistemas externos");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addComponent(jButton1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
            .addComponent(jButton2)
            .addGap(18, 18, 18)
            .addComponent(jButton5)
            .addGap(24, 24, 24))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jButton5)
                .addComponent(jButton2))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel5.setText("Unidade");

    unidadejTextField.setEnabled(false);

    selecionarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selecionar.png"))); // NOI18N
    selecionarjButton.setText("Selecionar");
    selecionarjButton.setToolTipText("Selecionar Cliente");
    selecionarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            selecionarjButtonActionPerformed(evt);
        }
    });

    jLabel6.setText("Cliente");

    jLabel7.setText("Data Venda");

    dataVendajDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataVendajDateChooserdataIniciojDateChooserFocusGained(evt);
        }
    });

    jLabel14.setText("Produto");

    jLabel15.setText("Total Bruto");

    totalBrutojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    totalBrutojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            totalBrutojTextFieldFocusLost(evt);
        }
    });
    totalBrutojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            totalBrutojTextFieldvalorjTextFieldKeyTyped(evt);
        }
    });

    jLabel16.setText("Valor Desconto");

    valorDescontojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorDescontojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            valorDescontojTextFieldFocusLost(evt);
        }
    });
    valorDescontojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            valorDescontojTextFieldvalorjTextField1KeyTyped(evt);
        }
    });

    totalLiquidojTextField.setEditable(false);
    totalLiquidojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    totalLiquidojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            totalLiquidojTextFieldvalorjTextField2KeyTyped(evt);
        }
    });

    jLabel17.setText("Total");

    jLabel21.setText("Consultor de Vendas");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(clientejTextField)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(unidadejTextField)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(selecionarjButton))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataVendajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(totalBrutojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(valorDescontojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(totalLiquidojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addComponent(produtojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel21))
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(consultorjTextField))
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(unidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(selecionarjButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel6)
            .addGap(1, 1, 1)
            .addComponent(clientejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel14)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(produtojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel21)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalBrutojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorDescontojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalLiquidojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dataVendajDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(consultorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );

    jTabbedPane1.addTab("Dados da Venda", jPanel4);

    jLabel11.setText("Comissão Funcionários");

    comissaoLiquidajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    comissaoLiquidajTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            comissaoLiquidajTextFieldFocusLost(evt);
        }
    });
    comissaoLiquidajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            comissaoLiquidajTextFieldKeyTyped(evt);
        }
    });

    comissaoFuncionariojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    comissaoFuncionariojTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            comissaoFuncionariojTextFieldFocusLost(evt);
        }
    });
    comissaoFuncionariojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            comissaoFuncionariojTextFieldKeyTyped(evt);
        }
    });

    jLabel12.setText("Comissão Liquida");

    despesasFinanceirajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    despesasFinanceirajTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            despesasFinanceirajTextFieldFocusLost(evt);
        }
    });
    despesasFinanceirajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            despesasFinanceirajTextFieldKeyTyped(evt);
        }
    });

    jLabel13.setText("Despesas Financeiras");

    jLabel25.setText("Comissão Terceiros");

    comissaoTerceirosjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    comissaoTerceirosjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            comissaoTerceirosjTextFieldFocusLost(evt);
        }
    });
    comissaoTerceirosjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            comissaoTerceirosjTextFieldKeyTyped(evt);
        }
    });

    jLabel27.setText("Data Pagto Fornecedor");

    dataPagamentoFornecedorjDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataPagamentoFornecedorjDateChooserdataIniciojDateChooserFocusGained(evt);
        }
    });

    totalVendajTextField.setEditable(false);
    totalVendajTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    totalVendajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            totalVendajTextFieldKeyTyped(evt);
        }
    });

    jLabel26.setText("Total");

    jLabel28.setText("Valor Pago Fornecedor");

    valorPagoFornecedorjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorPagoFornecedorjTextField.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            valorPagoFornecedorjTextFieldFocusLost(evt);
        }
    });
    valorPagoFornecedorjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            valorPagoFornecedorjTextFieldKeyPressed(evt);
        }
        public void keyReleased(java.awt.event.KeyEvent evt) {
            valorPagoFornecedorjTextFieldKeyReleased(evt);
        }
        public void keyTyped(java.awt.event.KeyEvent evt) {
            valorPagoFornecedorjTextFieldKeyTyped(evt);
        }
    });

    valorReceberjLabel.setText("Líquido de Venda");

    LiquidoVendaojTextField.setEditable(false);
    LiquidoVendaojTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    LiquidoVendaojTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            LiquidoVendaojTextFieldKeyTyped(evt);
        }
    });

    jLabel2.setText("Nome do Fornecedor");

    jLabel30.setText("Líquido Pagar / Receber");

    pagarReceberjTextField.setEditable(false);
    pagarReceberjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    pagarReceberjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            pagarReceberjTextFieldKeyTyped(evt);
        }
    });

    jLabel22.setText("Observações");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(comissaoLiquidajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(comissaoTerceirosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addComponent(dataPagamentoFornecedorjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel26)
                                .addComponent(totalVendajTextField)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(despesasFinanceirajTextField))
                            .addGap(58, 58, 58)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comissaoFuncionariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))))
                    .addGap(0, 1, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomefornecedorjTextField)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel22)
                                .addComponent(observacoesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorReceberjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LiquidoVendaojTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pagarReceberjTextField)
                        .addComponent(valorPagoFornecedorjTextField))))
            .addGap(18, 18, 18))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comissaoLiquidajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(despesasFinanceirajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comissaoFuncionariojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comissaoTerceirosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(jLabel26))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dataPagamentoFornecedorjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(totalVendajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel28)
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(valorPagoFornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nomefornecedorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(valorReceberjLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(LiquidoVendaojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel30)
                .addComponent(jLabel22))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(pagarReceberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(observacoesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab("Back Office", jPanel2);

    formajTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Tipo Documento", "Data Vencimento", "No. Parcelas", "Valor "
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane1.setViewportView(formajTable);
    if (formajTable.getColumnModel().getColumnCount() > 0) {
        formajTable.getColumnModel().getColumn(0).setResizable(false);
        formajTable.getColumnModel().getColumn(1).setResizable(false);
        formajTable.getColumnModel().getColumn(3).setResizable(false);
    }

    BarradeTarefasjToolBar.setFloatable(false);
    BarradeTarefasjToolBar.setRollover(true);

    adicionarAPagarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/adicionar.png"))); // NOI18N
    adicionarAPagarjButton.setText("Adicionar");
    adicionarAPagarjButton.setToolTipText("Adicionar Forma de Pagamento");
    adicionarAPagarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    adicionarAPagarjButton.setMaximumSize(new java.awt.Dimension(80, 90));
    adicionarAPagarjButton.setMinimumSize(new java.awt.Dimension(80, 90));
    adicionarAPagarjButton.setName(""); // NOI18N
    adicionarAPagarjButton.setPreferredSize(new java.awt.Dimension(80, 90));
    adicionarAPagarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    adicionarAPagarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            adicionarAPagarjButtonActionPerformed(evt);
        }
    });
    BarradeTarefasjToolBar.add(adicionarAPagarjButton);

    excluirAPagarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/excluir.png"))); // NOI18N
    excluirAPagarjButton.setText("Excluir");
    excluirAPagarjButton.setToolTipText("Excluir Forma de Pagamento");
    excluirAPagarjButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    excluirAPagarjButton.setMaximumSize(new java.awt.Dimension(80, 90));
    excluirAPagarjButton.setMinimumSize(new java.awt.Dimension(80, 90));
    excluirAPagarjButton.setPreferredSize(new java.awt.Dimension(80, 90));
    excluirAPagarjButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    excluirAPagarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            excluirAPagarjButtonActionPerformed(evt);
        }
    });
    BarradeTarefasjToolBar.add(excluirAPagarjButton);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(BarradeTarefasjToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE)))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(120, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(BarradeTarefasjToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap()))
    );

    jTabbedPane1.addTab("Forma de Recebimento", jPanel1);

    jLabel1.setText("Nome Completo");

    jLabel3.setText("Enderço");

    jLabel4.setText("Complemento");

    jLabel8.setText("Bairro");

    jLabel9.setText("Cidade");

    jLabel10.setText("Estado");

    estadojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RS", "RR", "SC", "SE", "SP", "TO" }));

    jLabel18.setText("CEP");

    jLabel19.setText("CNPJ/CPF");

    jLabel20.setText("I.E");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nomejTextField)
                .addComponent(enderecojTextField)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bairrojTextField)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(63, 63, 63)
                                    .addComponent(jLabel18))
                                .addComponent(jLabel8)
                                .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 112, Short.MAX_VALUE))))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cidadejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(cnpjjTextField))
                        .addComponent(jLabel19))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(iejTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(cepjFormattedTextField)))))
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(enderecojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jLabel8))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(complementojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bairrojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(jLabel10)
                .addComponent(jLabel18))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cepjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel19)
                .addComponent(jLabel20))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cnpjjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(iejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
    );

    jTabbedPane1.addTab("Nota Fiscal", jPanel3);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane1)
            .addContainerGap())
        .addGroup(layout.createSequentialGroup()
            .addGap(57, 57, 57)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jTabbedPane1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        salvarVenda();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void dataVendajDateChooserdataIniciojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataVendajDateChooserdataIniciojDateChooserFocusGained

    }//GEN-LAST:event_dataVendajDateChooserdataIniciojDateChooserFocusGained

    private void totalBrutojTextFieldvalorjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalBrutojTextFieldvalorjTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_totalBrutojTextFieldvalorjTextFieldKeyTyped

    private void valorDescontojTextFieldvalorjTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldvalorjTextField1KeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_valorDescontojTextFieldvalorjTextField1KeyTyped

    private void totalLiquidojTextFieldvalorjTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalLiquidojTextFieldvalorjTextField2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_totalLiquidojTextFieldvalorjTextField2KeyTyped

    private void comissaoLiquidajTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comissaoLiquidajTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_comissaoLiquidajTextFieldKeyTyped

    private void comissaoFuncionariojTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comissaoFuncionariojTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_comissaoFuncionariojTextFieldKeyTyped

    private void despesasFinanceirajTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_despesasFinanceirajTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_despesasFinanceirajTextFieldKeyTyped

    private void comissaoTerceirosjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comissaoTerceirosjTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_comissaoTerceirosjTextFieldKeyTyped

    private void dataPagamentoFornecedorjDateChooserdataIniciojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataPagamentoFornecedorjDateChooserdataIniciojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataPagamentoFornecedorjDateChooserdataIniciojDateChooserFocusGained

    private void totalBrutojTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalBrutojTextFieldFocusLost
        calcularValoresTotais();
    }//GEN-LAST:event_totalBrutojTextFieldFocusLost

    private void valorDescontojTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorDescontojTextFieldFocusLost
        calcularValoresTotais();
    }//GEN-LAST:event_valorDescontojTextFieldFocusLost

    private void valorPagoFornecedorjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorPagoFornecedorjTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_valorPagoFornecedorjTextFieldKeyTyped

    private void valorPagoFornecedorjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorPagoFornecedorjTextFieldKeyReleased
        
    }//GEN-LAST:event_valorPagoFornecedorjTextFieldKeyReleased

    private void valorPagoFornecedorjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorPagoFornecedorjTextFieldKeyPressed
        
    }//GEN-LAST:event_valorPagoFornecedorjTextFieldKeyPressed

    private void selecionarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarjButtonActionPerformed
        new FrmConsultaCliente(usuarioLogadoBean, this);
    }//GEN-LAST:event_selecionarjButtonActionPerformed

    private void adicionarAPagarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarAPagarjButtonActionPerformed
        Float totalLiquido = 0.0f;
        Float pagametnoFornecedor = 0.0f;
        if (totalLiquidojTextField.getText().length()>0){
            totalLiquido = Formatacao.ConvercaoMonetariaFloat(totalLiquidojTextField.getText());
        }
        if (valorPagoFornecedorjTextField.getText().length()>0){
            pagametnoFornecedor= Formatacao.ConvercaoMonetariaFloat(valorPagoFornecedorjTextField.getText());
        }
        Float total = totalLiquido - pagametnoFornecedor;
        new FrmLancarFormaPagamento(clientejTextField.getText(), Formatacao.foramtarFloatString(total), this);
    }//GEN-LAST:event_adicionarAPagarjButtonActionPerformed

    private void excluirAPagarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAPagarjButtonActionPerformed
        int linha = formajTable.getSelectedRow();
        if (linha>=0){
            if (listaForma.get(linha).getIdformaPagamento()!=null){
                FormaPagamentoController formaPagamentoController = new FormaPagamentoController();
                formaPagamentoController.Excluir(listaForma.get(linha).getIdformaPagamento());
                listaForma.remove(linha);
            }else {
                listaForma.remove(linha);
            }
            carregarFormaPagamento();
        }else JOptionPane.showMessageDialog(rootPane, " Selecione uma Forma de Pagamento");
    }//GEN-LAST:event_excluirAPagarjButtonActionPerformed

    private void despesasFinanceirajTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_despesasFinanceirajTextFieldFocusLost
        calcularValoresTotais();
    }//GEN-LAST:event_despesasFinanceirajTextFieldFocusLost

    private void comissaoFuncionariojTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comissaoFuncionariojTextFieldFocusLost
        calcularValoresTotais();
    }//GEN-LAST:event_comissaoFuncionariojTextFieldFocusLost

    private void comissaoTerceirosjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comissaoTerceirosjTextFieldFocusLost
        calcularValoresTotais();
    }//GEN-LAST:event_comissaoTerceirosjTextFieldFocusLost

    private void pagarReceberjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagarReceberjTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pagarReceberjTextFieldKeyTyped

    private void valorPagoFornecedorjTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorPagoFornecedorjTextFieldFocusLost
        calcularValoresTotais();
    }//GEN-LAST:event_valorPagoFornecedorjTextFieldFocusLost

    private void LiquidoVendaojTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LiquidoVendaojTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_LiquidoVendaojTextFieldKeyTyped

    private void comissaoLiquidajTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comissaoLiquidajTextFieldFocusLost
        calcularValoresTotais();
    }//GEN-LAST:event_comissaoLiquidajTextFieldFocusLost

    private void totalVendajTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalVendajTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_totalVendajTextFieldKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        importaVenda();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar BarradeTarefasjToolBar;
    private javax.swing.JTextField LiquidoVendaojTextField;
    private javax.swing.JButton adicionarAPagarjButton;
    private javax.swing.JTextField bairrojTextField;
    private javax.swing.JFormattedTextField cepjFormattedTextField;
    private javax.swing.JTextField cidadejTextField;
    private javax.swing.JTextField clientejTextField;
    private javax.swing.JTextField cnpjjTextField;
    private javax.swing.JTextField comissaoFuncionariojTextField;
    private javax.swing.JTextField comissaoLiquidajTextField;
    private javax.swing.JTextField comissaoTerceirosjTextField;
    private javax.swing.JTextField complementojTextField;
    private javax.swing.JTextField consultorjTextField;
    private com.toedter.calendar.JDateChooser dataPagamentoFornecedorjDateChooser;
    private com.toedter.calendar.JDateChooser dataVendajDateChooser;
    private javax.swing.JTextField despesasFinanceirajTextField;
    private javax.swing.JTextField enderecojTextField;
    private javax.swing.JComboBox estadojComboBox;
    private javax.swing.JButton excluirAPagarjButton;
    private javax.swing.JTable formajTable;
    private javax.swing.JTextField iejTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nomefornecedorjTextField;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JTextField observacoesjTextField;
    private javax.swing.JTextField pagarReceberjTextField;
    private javax.swing.JComboBox produtojComboBox;
    private javax.swing.JButton selecionarjButton;
    private javax.swing.JTextField totalBrutojTextField;
    private javax.swing.JTextField totalLiquidojTextField;
    private javax.swing.JTextField totalVendajTextField;
    private javax.swing.JTextField unidadejTextField;
    private javax.swing.JTextField valorDescontojTextField;
    private javax.swing.JTextField valorPagoFornecedorjTextField;
    private javax.swing.JLabel valorReceberjLabel;
    // End of variables declaration//GEN-END:variables

    public void inicilizarNovaVendas() {
        ClienteController clienteController = new ClienteController();
        this.venda = new Vendas();
        this.venda.setValorBruto(0.0f);
        this.venda.setValorDesconto(0.0f);
        this.venda.setValorLiquido(0.0f);
        this.venda.setComissaoFuncionarios(0.0f);
        this.venda.setComissaoLiquidaTotal(0.0f);
        this.venda.setComissaoTerceiros(0.0f);
        this.venda.setDespesasFinanceiras(0.0f);
        this.venda.setValorPagoFornecedor(0.0f);
        this.venda.setValorRecebido(0.0f);
        if (usuarioLogadoBean.getUsuario().getCliente() > 0) {
            selecionarjButton.setEnabled(false);
            cliente = clienteController.consultar(usuarioLogadoBean.getUsuario().getCliente());
            unidadejTextField.setText(cliente.getNomeFantasia());
            carregarComboBox(cliente.getIdcliente());
        }
        carregarFormaPagamento();
    }
    
    public void inicilizarEditarVendas(int idVenda) {
        ClienteController clienteController = new ClienteController();
        VendasController vendasController = new VendasController();
        this.venda = vendasController.consultar(idVenda);
        if (venda!=null){
            selecionarjButton.setEnabled(false);
            cliente = clienteController.consultar(venda.getCliente());
            unidadejTextField.setText(cliente.getNomeFantasia());
            carregarComboBox(cliente.getIdcliente());
            clientejTextField.setText(venda.getNomeCliente());
            ProdutoController produtoController = new ProdutoController();
            Produto produto = produtoController.consultar(venda.getProduto());
            produtojComboBox.setSelectedItem(produto);
            dataVendajDateChooser.setDate(venda.getDataVenda());
            totalBrutojTextField.setText(Formatacao.foramtarFloatString(venda.getValorBruto()));
            valorDescontojTextField.setText(Formatacao.foramtarFloatString(venda.getValorDesconto()));
            totalLiquidojTextField.setText(Formatacao.foramtarFloatString(venda.getValorLiquido()));
            comissaoLiquidajTextField.setText(Formatacao.foramtarFloatString(venda.getComissaoLiquidaTotal()));
            despesasFinanceirajTextField.setText(Formatacao.foramtarFloatString(venda.getDespesasFinanceiras()));
            comissaoFuncionariojTextField.setText(Formatacao.foramtarFloatString(venda.getComissaoFuncionarios()));
            comissaoTerceirosjTextField.setText(Formatacao.foramtarFloatString(venda.getComissaoTerceiros()));
            dataPagamentoFornecedorjDateChooser.setDate(venda.getDataPagamentoFornecedor());
            valorPagoFornecedorjTextField.setText(Formatacao.foramtarFloatString(venda.getValorPagoFornecedor()));
            nomefornecedorjTextField.setText(venda.getNomeFornecedor());
            consultorjTextField.setText(venda.getConsultor());
            observacoesjTextField.setText(venda.getObservacao());
            calcularValoresTotais();
            if (venda.getEmissaonota()!=null){
                nomejTextField.setText(venda.getEmissaonota().getNome());
                enderecojTextField.setText(venda.getEmissaonota().getEndereco());
                complementojTextField.setText(venda.getEmissaonota().getComplemento());
                bairrojTextField.setText(venda.getEmissaonota().getBairro());
                cidadejTextField.setText(venda.getEmissaonota().getCidade());
                cepjFormattedTextField.setText(venda.getEmissaonota().getCep());
                estadojComboBox.setSelectedItem(venda.getEmissaonota().getEstado());
                cnpjjTextField.setText(venda.getEmissaonota().getCpnj());
                iejTextField.setText(venda.getEmissaonota().getIe());
            }
        }
        carregarFormaPagamento();
    }
    
    public void carregarComboBox(int idCliente){
        ProdutoController produtoController = new ProdutoController();
        List<Produto> listaProduto = produtoController.listar(idCliente);
        if (listaProduto!=null){
            produtojComboBox = Formatacao.preencherComobox(listaProduto, produtojComboBox);
        }
    }
    
    public void salvarVenda(){
        venda.setCliente(cliente.getIdcliente());
        venda.setNomeCliente(clientejTextField.getText());
        venda.setDataVenda(dataVendajDateChooser.getDate());
        venda.setPlanoContas(cliente.getContaReceita());
        if (comissaoFuncionariojTextField.getText().length()>0){
            venda.setComissaoFuncionarios(Formatacao.formatarStringfloat(comissaoFuncionariojTextField.getText()));
        }else venda.setComissaoFuncionarios(0.0f);
        if (comissaoLiquidajTextField.getText().length()>0){
            venda.setComissaoLiquidaTotal(Formatacao.formatarStringfloat(comissaoLiquidajTextField.getText()));
        }else venda.setComissaoLiquidaTotal(0.0f);
        if (comissaoTerceirosjTextField.getText().length()>0){
            venda.setComissaoTerceiros(Formatacao.formatarStringfloat(comissaoTerceirosjTextField.getText()));
        }else venda.setComissaoTerceiros(0.0f);
        if (despesasFinanceirajTextField.getText().length()>0){
            venda.setDespesasFinanceiras(Formatacao.formatarStringfloat(despesasFinanceirajTextField.getText()));
        }else venda.setDespesasFinanceiras(0.0f);
        if (totalBrutojTextField.getText().length()>0){
            venda.setValorBruto(Formatacao.formatarStringfloat(totalBrutojTextField.getText()));
        }else venda.setValorBruto(0.0f);
        
        if (totalLiquidojTextField.getText().length()>0){
            venda.setValorLiquido(Formatacao.formatarStringfloat(totalLiquidojTextField.getText()));
        }else venda.setValorLiquido(0.0f);
         if (LiquidoVendaojTextField.getText().length()>0){
            venda.setLiquidoVendas(Formatacao.formatarStringfloat(LiquidoVendaojTextField.getText()));
        }else venda.setLiquidoVendas(0.0f);
        if (valorDescontojTextField.getText().length()>0){
            venda.setValorDesconto(Formatacao.formatarStringfloat(valorDescontojTextField.getText()));
        }else venda.setValorDesconto(0.0f);
        
        if (valorPagoFornecedorjTextField.getText().length()>0){
            venda.setValorPagoFornecedor(Formatacao.formatarStringfloat(valorPagoFornecedorjTextField.getText()));
        }else venda.setValorPagoFornecedor(0.0f);
        if (LiquidoVendaojTextField.getText().length()>0){
            venda.setValorRecebido(Formatacao.formatarStringfloat(LiquidoVendaojTextField.getText()));
        }else venda.setValorRecebido(0.0f);
        if (dataVendajDateChooser.getDate()!=null){
            venda.setDataVenda(dataVendajDateChooser.getDate());
        }
        if (dataPagamentoFornecedorjDateChooser.getDate()!=null){
           venda.setDataPagamentoFornecedor(dataPagamentoFornecedorjDateChooser.getDate());
        }
       if (pagarReceberjTextField.getText().length()>0){
            venda.setLiquidoReceber(Formatacao.ConvercaoMonetariaFloat(pagarReceberjTextField.getText()));
        }else venda.setLiquidoReceber(0.0f);
       if (dataPagamentoFornecedorjDateChooser.getDate()!=null){
           venda.setDataPagamentoFornecedor(dataPagamentoFornecedorjDateChooser.getDate());
       }
       venda.setObservacao(observacoesjTextField.getText());
        venda.setConsultor(consultorjTextField.getText());
        venda.setNomeFornecedor(nomefornecedorjTextField.getText());
        venda.setUsuario(usuarioLogadoBean.getUsuario().getIdusuario());
        Produto produto = (Produto) produtojComboBox.getSelectedItem();
        venda.setProduto(produto.getIdproduto());
        if (venda.getSituacao() != null) {
            if (!venda.getSituacao().equalsIgnoreCase("verde")) {
                if (listaForma != null) {
                    if (listaForma.size() > 0) {
                        venda.setSituacao("amarelo");
                    } else {
                        venda.setSituacao("vermelho");
                    }
                } else {
                    venda.setSituacao("vermenlho");
                }
            }
        } else {
            if (listaForma != null) {
                if (listaForma.size() > 0) {
                    venda.setSituacao("amarelo");
                } else {
                    venda.setSituacao("vermelho");
                }
            } else {
                venda.setSituacao("vermenlho");
            }
        }
        if (nomejTextField.getText().length() > 0) {
            Emissaonota emissao = null;
            if (venda.getEmissaonota() == null) {
                emissao = new Emissaonota();
            } else {
                emissao = venda.getEmissaonota();
            }
            emissao.setNome(nomejTextField.getText());
            emissao.setEndereco(enderecojTextField.getText());
            emissao.setComplemento(complementojTextField.getText());
            emissao.setBairro(bairrojTextField.getText());
            emissao.setEstado(estadojComboBox.getSelectedItem().toString());
            emissao.setCep(cepjFormattedTextField.getText());
            emissao.setCpnj(cnpjjTextField.getText());
            emissao.setIe(iejTextField.getText());
            emissao.setVendas(venda);
            venda.setEmissaonota(emissao);
        }
        VendasController vendasController = new VendasController();
        venda= vendasController.salvar(venda);
        if (listaForma!=null){
            FormaPagamentoController formaPagamentoController = new FormaPagamentoController();
            for (int i=0;i<listaForma.size();i++){
                Formapagamento forma = listaForma.get(i);
                forma.setVendas(venda.getIdvendas());
                formaPagamentoController.salvar(forma);
            }
        }
        
        this.telaVednas.setModel();
        this.dispose();
    }

    @Override
    public void setModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setCliente(Cliente cliente) {
        if (cliente!=null){
            if (cliente.getContaReceita()>0){
                this.cliente = cliente;
                unidadejTextField.setText(cliente.getNomeFantasia());
                carregarComboBox(cliente.getIdcliente());
            }else {
                JOptionPane.showMessageDialog(rootPane, "Conta Receita não selecionada");
            }
            
        }
    }
    
    public void carregarFormaPagamento(){
        if (listaForma == null) {
            if (venda.getIdvendas() != null) {
                FormaPagamentoController formaPagamentoController = new FormaPagamentoController();
                listaForma = formaPagamentoController.listar(venda.getIdvendas());
            }
            if (listaForma == null) {
                listaForma = new ArrayList<Formapagamento>();
            }
        }
        modelForma = new ConsultaFormaPagamentoTableModel(listaForma);
        formajTable.setModel(modelForma);
        DefaultTableCellRenderer rendererValor = new DefaultTableCellRenderer();
        rendererValor.setHorizontalAlignment(SwingConstants.RIGHT);
        formajTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        formajTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        formajTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        formajTable.getColumnModel().getColumn(3).setCellRenderer(rendererValor);
        formajTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        formajTable.repaint();
    }

    @Override
    public void setArquivo(File arquivo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setFormaPagamento(Formapagamento formaPagamento) {
        if (formaPagamento!=null){
            listaForma.add(formaPagamento);
            carregarFormaPagamento();
        }
    }
    
    
    
    private void calcularValoresTotais(){
        float comissaoLiquida = 0.0f;
        float despesasFinanceiras = 0.0f;
        float comissaoFuncionarios = 0.0f;
        float comissaoTerceiros = 0.0f;
        float valorBruto = 0.0f;
        float valorDesconto = 0.0f;
        float totalLiquido = 0.0f;
        float valorFornecedor = 0.0f;
        float liquidoVendas = 0.0f;
        float pagarReceber = 0.0f;
        if (totalBrutojTextField.getText().length()>0){
            valorBruto = Formatacao.formatarStringfloat(totalBrutojTextField.getText());
        }
        if (valorDescontojTextField.getText().length()>0){
            valorDesconto = Formatacao.formatarStringfloat(valorDescontojTextField.getText());
        }
        totalLiquido =  valorBruto - valorDesconto;
        totalLiquidojTextField.setText(Formatacao.foramtarFloatString(totalLiquido));
        totalVendajTextField.setText(Formatacao.foramtarFloatString(totalLiquido));
        if (comissaoLiquidajTextField.getText().length()>0){
            comissaoLiquida = Formatacao.formatarStringfloat(comissaoLiquidajTextField.getText());
        }
        if (despesasFinanceirajTextField.getText().length()>0){
            despesasFinanceiras = Formatacao.formatarStringfloat(despesasFinanceirajTextField.getText());
        }
        if (comissaoFuncionariojTextField.getText().length()>0){
            comissaoFuncionarios = Formatacao.formatarStringfloat(comissaoFuncionariojTextField.getText());
        }
        if (comissaoTerceirosjTextField.getText().length()>0){
            comissaoTerceiros = Formatacao.formatarStringfloat(comissaoTerceirosjTextField.getText());
        }
        liquidoVendas = comissaoLiquida - (despesasFinanceiras + comissaoFuncionarios + comissaoTerceiros);
        if (valorPagoFornecedorjTextField.getText().length()>0){
            valorFornecedor = Formatacao.formatarStringfloat(valorPagoFornecedorjTextField.getText());
        }
        pagarReceber = valorBruto - (comissaoLiquida + valorFornecedor);
        LiquidoVendaojTextField.setText(Formatacao.foramtarFloatString(liquidoVendas));
        pagarReceberjTextField.setText(Formatacao.foramtarFloatString(pagarReceber));
    }

    @Override
    public void exportarExcel(String caminho, String nomeArquivo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void inicializarCliente(){
        this.cliente = Formatacao.consultarCliente(usuarioLogadoBean);
        if (cliente!=null){
            unidadejTextField.setText(cliente.getNomeFantasia());
            selecionarjButton.setEnabled(false);
        }
    }
    
    public void importaVenda(){
        boolean validar = false;
        int numeroVenda = Integer.parseInt(JOptionPane.showInputDialog("Informe o Número da Venda"));
        IntegracaoController integracaoController = new IntegracaoController();
        Viewvendasintegracao sVenda = integracaoController.consultarVendas(numeroVenda);
        if (sVenda != null) {
            cliente = integracaoController.consultarClietne(sVenda.getUnidadeNegocioidunidadeNegocio());
            Produto produto = null;
            if (cliente != null) {
                carregarComboBox(cliente.getIdcliente());
                validar = true;
                produto = integracaoController.consultarProduto(cliente.getIdcliente(), sVenda.getProdutosIdprodutos());
                if (produto != null) {
                    validar = true;
                } else {
                    validar = false;
                    JOptionPane.showMessageDialog(rootPane, "Produto não Localizado");
                }
            } else {
                validar = false;
                JOptionPane.showMessageDialog(rootPane, "Unidade não Localizada");
            }
            if (validar) {
                List<SParcelamentopagamento> listaParcelamento = integracaoController.listarParcelmanetoFormaPagamento(sVenda.getIdformaPagamento());
                unidadejTextField.setText(cliente.getNomeFantasia());
                produtojComboBox.setSelectedItem(produto);
                dataVendajDateChooser.setDate(sVenda.getDataVenda());
                clientejTextField.setText(sVenda.getNomeCliente());
                if (listaParcelamento != null) {
                    for (int i = 0; i < listaParcelamento.size(); i++) {
                        Formapagamento forma = new Formapagamento();
                        String dataVencimento = JOptionPane.showInputDialog("Informe Data Vencimento");
                        forma.setDataVencimento(Formatacao.ConvercaoStringDataBrasil(dataVencimento));
                        forma.setNomeCliente(clientejTextField.getText());
                        forma.setNumeroParcelas(listaParcelamento.get(i).getNumeroParcelas());
                        forma.setTipoDocumento(listaParcelamento.get(i).getFormaPagamento());
                        forma.setValor(listaParcelamento.get(i).getValorParcelamento());
                        forma.setValorParcela(listaParcelamento.get(i).getValorParcela());
                        listaForma.add(forma);
                    }
                }
                Orcamentoprodutosorcamento produtoOrcamento = integracaoController.consultarOrcamentoProdutoOrcamento(sVenda.getIdorcamento(), 5);
                Float valorSeguroAssist = 0.0f;
                if (produtoOrcamento != null) {
                    valorSeguroAssist = produtoOrcamento.getValorMoedaNacional();
                }
                produtoOrcamento = integracaoController.consultarOrcamentoProdutoOrcamento(sVenda.getIdorcamento(), 21);
                Float valorSeguroGoveramental = 0.0f;
                if (produtoOrcamento != null) {
                    valorSeguroGoveramental = produtoOrcamento.getValorMoedaNacional();
                }
                produtoOrcamento = integracaoController.consultarOrcamentoProdutoOrcamento(sVenda.getIdorcamento(), 9);
                Float valorDesconto = 0.0f;
                if (produtoOrcamento != null) {
                    valorDesconto = produtoOrcamento.getValorMoedaNacional();
                }
                Float valorTotalVenda = (sVenda.getTotalMoedaNacional() - valorDesconto + sVenda.getValorJuros()) - (valorSeguroAssist + valorSeguroGoveramental);
                totalBrutojTextField.setText(Formatacao.foramtarFloatString(valorTotalVenda));
                String vd = Formatacao.foramtarFloatString(valorDesconto);
                valorDescontojTextField.setText(Formatacao.retirarNegativo(vd));
                totalLiquidojTextField.setText(Formatacao.foramtarFloatString(sVenda.getTotalMoedaNacional() + sVenda.getValorJuros()));
                carregarFormaPagamento();
            }
        }
    }
    
    @Override
    public void pesquisar(String sql, String order ) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setNumeroColuna(int numero) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void limitarJText() {
        cidadejTextField.setDocument(new LimiteTextoJedit(50));
        observacoesjTextField.setDocument(new LimiteTextoJedit(100));
        nomejTextField.setDocument(new LimiteTextoJedit(100));
        enderecojTextField.setDocument(new LimiteTextoJedit(100));
        complementojTextField.setDocument(new LimiteTextoJedit(50));
        bairrojTextField.setDocument(new LimiteTextoJedit(50));
        cidadejTextField.setDocument(new LimiteTextoJedit(50));
        cnpjjTextField.setDocument(new LimiteTextoJedit(18));
        iejTextField.setDocument(new LimiteTextoJedit(30));
    }
}
