/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tela.ContasPagar;

import com.toedter.calendar.JTextFieldDateEditor;
import controller.BancoController;
import controller.ContasPagarController;
import controller.PlanoContasController;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Arquivocontaspagar;
import model.Banco;
import model.Cliente;
import model.Contaspagar;
import model.Planocontas;
import tela.Cliente.FrmConsultaCliente;
import tela.util.Formatacao;
import tela.util.UsuarioLogadoBean;

/**
 *
 * @author Wolverine
 */
public class FrmCadastarContasPagar extends javax.swing.JFrame implements IContasPagar{
    
    private String datePattern;
    private String maskPattern;
    private char placeHolder;
    private UsuarioLogadoBean usuarioLogadoBean;
    private Contaspagar conta;
    private Cliente cliente;
    private IContasPagar telaContas;
    private Arquivocontaspagar arquivoConta;
    

    /**
     * Creates new form FrmCadastarContasPgar
     */
    public FrmCadastarContasPagar(UsuarioLogadoBean usuarioLogadoBean, Contaspagar conta, IContasPagar telaContas) {
        datePattern = "dd/MM/yyyy";
        maskPattern = "##/##/####";
        placeHolder = '_';
        this.usuarioLogadoBean = usuarioLogadoBean;
        this.telaContas = telaContas;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logoRelatorio/iconetela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        inicilizarContasPagar(conta);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dataEnviojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
            maskPattern, placeHolder));
    jLabel4 = new javax.swing.JLabel();
    dataAgendamentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jScrollPane1 = new javax.swing.JScrollPane();
descricaojTextArea = new javax.swing.JTextArea();
planoContasjComboBox = new javax.swing.JComboBox();
jLabel1 = new javax.swing.JLabel();
jLabel2 = new javax.swing.JLabel();
jLabel6 = new javax.swing.JLabel();
contajComboBox = new javax.swing.JComboBox();
jLabel7 = new javax.swing.JLabel();
dataCompensacaojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
    maskPattern, placeHolder));
    jLabel8 = new javax.swing.JLabel();
    valorjTextField = new javax.swing.JTextField();
    competenciajFormattedTextField = new javax.swing.JFormattedTextField();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    dataVencimentojDateChooser = new com.toedter.calendar.JDateChooser(null, null, datePattern, new JTextFieldDateEditor(datePattern,
        maskPattern, placeHolder));
jLabel11 = new javax.swing.JLabel();
unidadejTextField = new javax.swing.JTextField();
selecionarjButton = new javax.swing.JButton();
jLabel12 = new javax.swing.JLabel();
arquivo01jTextField = new javax.swing.JTextField();
jButton3 = new javax.swing.JButton();
jLabel13 = new javax.swing.JLabel();
formaPagamentojComboBox = new javax.swing.JComboBox();
arquivo02jTextField = new javax.swing.JTextField();
jButton4 = new javax.swing.JButton();
jLabel5 = new javax.swing.JLabel();
fornecedorjTextField = new javax.swing.JTextField();
tipoDocumentojComboBox = new javax.swing.JComboBox();
jLabel14 = new javax.swing.JLabel();
numeroDocumentojTextField = new javax.swing.JTextField();
jLabel15 = new javax.swing.JLabel();
jPanel4 = new javax.swing.JPanel();
confirmajButton = new javax.swing.JButton();
jButton2 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
setTitle("Cadastrar Contas a Pagar");

jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

jLabel3.setText("Data Envio");

dataEnviojDateChooser.setEnabled(false);
dataEnviojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
    public void focusGained(java.awt.event.FocusEvent evt) {
        dataEnviojDateChooserFocusGained(evt);
    }
    });

    jLabel4.setText("Data Agendamento");

    dataAgendamentojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataAgendamentojDateChooserFocusGained(evt);
        }
    });

    descricaojTextArea.setColumns(20);
    descricaojTextArea.setLineWrap(true);
    descricaojTextArea.setRows(2);
    jScrollPane1.setViewportView(descricaojTextArea);

    jLabel1.setText("Plano de Contas");

    jLabel2.setText("Descrição");

    jLabel6.setText("Conta");

    jLabel7.setText("Data Compensação");

    dataCompensacaojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataCompensacaojDateChooserFocusGained(evt);
        }
    });

    jLabel8.setText("Valor R$");

    valorjTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    valorjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            valorjTextFieldKeyTyped(evt);
        }
    });

    competenciajFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##/####"))));
    competenciajFormattedTextField.setText("  /    ");
    competenciajFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            competenciajFormattedTextFieldKeyTyped(evt);
        }
    });

    jLabel9.setText("Competência");

    jLabel10.setText("Data Vencimento");

    dataVencimentojDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            dataVencimentojDateChooserFocusGained(evt);
        }
    });

    jLabel11.setText("Unidade");

    unidadejTextField.setEnabled(false);

    selecionarjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selecionar.png"))); // NOI18N
    selecionarjButton.setText("Selecionar");
    selecionarjButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            selecionarjButtonActionPerformed(evt);
        }
    });

    jLabel12.setText("Upload de Arquivo");

    arquivo01jTextField.setEnabled(false);

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selecionar.png"))); // NOI18N
    jButton3.setText("Carregar");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    jLabel13.setText("Forma de Pagamento");

    formaPagamentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cheque", "Dinheiro", "Boleto", "Cartão", "Debito em Conta", "Depósito" }));

    arquivo02jTextField.setEnabled(false);

    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selecionar.png"))); // NOI18N
    jButton4.setText("Carregar");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    jLabel5.setText("Fornecedor");

    tipoDocumentojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boleto", "Guia de Imposto", "Holerite", "Nota Fiscal", "Recibo", "Outros" }));

    jLabel14.setText("Tipo Documento");

    jLabel15.setText("No. Documento");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(404, 404, 404)
                    .addComponent(selecionarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(arquivo02jTextField)
                                .addComponent(arquivo01jTextField))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel5))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(fornecedorjTextField))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numeroDocumentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(69, 69, 69))
                                .addComponent(tipoDocumentojComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataEnviojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(dataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dataAgendamentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(dataCompensacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGap(302, 302, 302))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(planoContasjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(16, 16, 16)))
                    .addGap(15, 15, 15)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(valorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(contajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(formaPagamentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(competenciajFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel2))
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(unidadejTextField)
                    .addGap(125, 125, 125)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel12)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(arquivo01jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(arquivo02jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel11)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(selecionarjButton)
                .addComponent(unidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jLabel14)
                .addComponent(jLabel15))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fornecedorjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDocumentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroDocumentojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(dataEnviojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataCompensacaojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataVencimentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(dataAgendamentojDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(planoContasjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(valorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(competenciajFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(formaPagamentojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(23, 23, 23))
    );

    jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    confirmajButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/confirmar.png"))); // NOI18N
    confirmajButton.setText("Confirmar");
    confirmajButton.setToolTipText("Confirmar");
    confirmajButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            confirmajButtonActionPerformed(evt);
        }
    });

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoespequenos/cancel.png"))); // NOI18N
    jButton2.setText("Cancelar");
    jButton2.setToolTipText("Cancelar");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(confirmajButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
            .addComponent(jButton2)
            .addGap(34, 34, 34))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(confirmajButton)
                .addComponent(jButton2))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataEnviojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataEnviojDateChooserFocusGained

    }//GEN-LAST:event_dataEnviojDateChooserFocusGained

    private void dataAgendamentojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataAgendamentojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataAgendamentojDateChooserFocusGained

    private void dataCompensacaojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataCompensacaojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataCompensacaojDateChooserFocusGained

    private void confirmajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmajButtonActionPerformed
        salvarConta();
    }//GEN-LAST:event_confirmajButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dataVencimentojDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataVencimentojDateChooserFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dataVencimentojDateChooserFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new FrmCarregarArquivo(this, 1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void valorjTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorjTextFieldKeyTyped
        if (evt.getKeyChar()=='.'){
            evt.setKeyChar(',');
        }
        String caracteres = "0987654321,-";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_valorjTextFieldKeyTyped

    private void competenciajFormattedTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_competenciajFormattedTextFieldKeyTyped
        String caracteres = "0987654321/";
        if (evt.getKeyChar() != '\b') {
            if (!caracteres.contains(evt.getKeyChar() + "")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_competenciajFormattedTextFieldKeyTyped

    private void selecionarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarjButtonActionPerformed
        new FrmConsultaCliente(usuarioLogadoBean, this);
    }//GEN-LAST:event_selecionarjButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new FrmCarregarArquivo(this, 2);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arquivo01jTextField;
    private javax.swing.JTextField arquivo02jTextField;
    private javax.swing.JFormattedTextField competenciajFormattedTextField;
    private javax.swing.JButton confirmajButton;
    private javax.swing.JComboBox contajComboBox;
    private com.toedter.calendar.JDateChooser dataAgendamentojDateChooser;
    private com.toedter.calendar.JDateChooser dataCompensacaojDateChooser;
    private com.toedter.calendar.JDateChooser dataEnviojDateChooser;
    private com.toedter.calendar.JDateChooser dataVencimentojDateChooser;
    private javax.swing.JTextArea descricaojTextArea;
    private javax.swing.JComboBox formaPagamentojComboBox;
    private javax.swing.JTextField fornecedorjTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numeroDocumentojTextField;
    private javax.swing.JComboBox planoContasjComboBox;
    private javax.swing.JButton selecionarjButton;
    private javax.swing.JComboBox tipoDocumentojComboBox;
    private javax.swing.JTextField unidadejTextField;
    private javax.swing.JTextField valorjTextField;
    // End of variables declaration//GEN-END:variables

    public void inicilizarContasPagar(Contaspagar conta){
        try {           
            competenciajFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (ParseException ex) {
            Logger.getLogger(FrmCadastarContasPagar.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (conta!=null){
            this.conta = conta;
            ContasPagarController contasPagarController = new ContasPagarController();
            this.arquivoConta = contasPagarController.consultarArquivo(conta.getIdcontasPagar());
            if (arquivoConta!=null){
                arquivo01jTextField.setText(arquivoConta.getNomeArquivo01());
                arquivo02jTextField.setText(arquivoConta.getNomeArquivo02());
            }
            //cliente = clienteController.consultar(conta.getCliente());
            cliente = conta.getCliente();
            if (cliente!=null){
                carregarComboBox();
            }
            unidadejTextField.setText(cliente.getNomeFantasia());
            dataAgendamentojDateChooser.setDate(conta.getDataAgendamento());
            dataCompensacaojDateChooser.setDate(conta.getDataCompensacao());
            dataVencimentojDateChooser.setDate(conta.getDataVencimento());
            fornecedorjTextField.setText(conta.getFornecedor());
            numeroDocumentojTextField.setText(conta.getNumeroDocumento());
            tipoDocumentojComboBox.setSelectedItem(conta.getTipoDocumento());
            planoContasjComboBox.setSelectedItem(conta.getPlanocontas());
            descricaojTextArea.setText(conta.getDescricao());
            competenciajFormattedTextField.setText(conta.getCompetencia());
            valorjTextField.setText(Formatacao.foramtarFloatString(conta.getValor()));
            contajComboBox.setSelectedItem(conta.getBanco());
            dataEnviojDateChooser.setDate(conta.getDataEnvio());
            formaPagamentojComboBox.setSelectedItem(conta.getFormaPagamento());
            if (conta.getDataLiberacao()!=null){
                confirmajButton.setEnabled(false);
            }
            if (conta.getAutorizarPagamento().equalsIgnoreCase("N")){
                dataAgendamentojDateChooser.setEnabled(false);
                dataCompensacaojDateChooser.setEnabled(false);
            }
        }else {
            inicializarCliente();
            carregarComboBox();
            this.conta = new Contaspagar();
            this.conta.setMovimentoBanco(0);
            this.conta.setUsuarioAgendou(0);
            this.conta.setUsuarioBaixou(0);
            this.conta.setUsuarioCadastrou(0);
            this.conta.setContaPaga("N");
            this.conta.setMarcar("N");
            this.conta.setAutorizarPagamento("N");
            dataEnviojDateChooser.setDate(new Date());
        }
    }

    @Override
    public void setModel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setArquivo(File arquivo, int numeroArquivo) {
        if (arquivo != null) {
            if (this.arquivoConta==null){
                arquivoConta = new Arquivocontaspagar();
            }
            if (numeroArquivo == 1) {
                arquivo01jTextField.setText(arquivo.getAbsolutePath() + " " + arquivo.getName());
                try {
                    this.arquivoConta.setNomeArquivo01(arquivo.getName());
                    this.arquivoConta.setArquivo01(gerarArquivoBase(arquivo));
                } catch (IOException ex) {
                    Logger.getLogger(FrmCadastarContasPagar.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, "Erro Carregar Arquivo " + ex);
                }
            } else if (numeroArquivo == 2) {
                arquivo02jTextField.setText(arquivo.getAbsolutePath() + " " + arquivo.getName());
                try {
                    this.arquivoConta.setNomeArquivo02(arquivo.getName());
                    this.arquivoConta.setArquivo02(gerarArquivoBase(arquivo));
                } catch (IOException ex) {
                    Logger.getLogger(FrmCadastarContasPagar.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, "Erro Carregar Arquivo " + ex);
                }
            }
        }
    }
    
    public byte[] gerarArquivoBase(File file) throws IOException {
        InputStream is = new FileInputStream(file);
        byte[] xml = new byte[(int) file.length()];
        int offset = 0;
        int numRead = 0;
        while (offset < xml.length
                && (numRead = is.read(xml, offset, xml.length - offset)) >= 0) {
            offset += numRead;
        }
        return xml;
    }
    
    public void salvarConta(){
        if (conta.getIdcontasPagar()==null){
            conta.setUsuarioCadastrou(usuarioLogadoBean.getUsuario().getIdusuario());
            String data = Formatacao.ConvercaoDataPadrao(new Date()) + "_" + Formatacao.foramtarHoraString();
            conta.setDataHoraCadastrou(data);
        }
        if (dataAgendamentojDateChooser.getDate()!=null){
            if (conta.getUsuarioAgendou()==0){
                conta.setUsuarioAgendou(usuarioLogadoBean.getUsuario().getIdusuario());
                String data = Formatacao.ConvercaoDataPadrao(new Date()) + "_" + Formatacao.foramtarHoraString();
                conta.setDataHoraAgendou(data);
            }
        }
        if (dataAgendamentojDateChooser.getDate()!=null){
            conta.setDataAgendamento(dataAgendamentojDateChooser.getDate());
        }
        if (dataEnviojDateChooser.getDate()!=null){
            conta.setDataEnvio(dataEnviojDateChooser.getDate());
        }
        if (dataCompensacaojDateChooser.getDate()!=null){
            conta.setDataCompensacao(dataCompensacaojDateChooser.getDate());
        }
        if (dataVencimentojDateChooser.getDate()!=null){
            conta.setDataVencimento(dataVencimentojDateChooser.getDate());
        }
        Planocontas plano = (Planocontas) planoContasjComboBox.getSelectedItem();
        conta.setPlanocontas(plano);
        Banco banco = (Banco) contajComboBox.getSelectedItem();
        conta.setBanco(banco);
        conta.setDescricao(descricaojTextArea.getText());
        conta.setValor(Formatacao.ConvercaoMonetariaFloat(valorjTextField.getText()));
        conta.setCompetencia(competenciajFormattedTextField.getText());
        conta.setFormaPagamento(formaPagamentojComboBox.getSelectedItem().toString());
        conta.setCliente(cliente);
        conta.setFornecedor(fornecedorjTextField.getText());
        conta.setNumeroDocumento(numeroDocumentojTextField.getText());
        conta.setTipoDocumento(tipoDocumentojComboBox.getSelectedItem().toString());
        ContasPagarController contasPagarController = new ContasPagarController();
        conta = contasPagarController.salvar(conta);
        if (arquivoConta!=null){
            arquivoConta.setContaspagar(conta.getIdcontasPagar());
            contasPagarController.salvarArquivo(arquivoConta);
        }
        telaContas.setModel();
        this.dispose();
    }
    
    public void carregarComboBox() {
        if (cliente != null) {
            PlanoContasController planoContasController = new PlanoContasController();
            BancoController bancoController = new BancoController();
            List<Banco> listaBanco = bancoController.listar(cliente.getIdcliente());
            List<Planocontas> listaPlano = planoContasController.listar();
            if (listaBanco != null) {
                contajComboBox = Formatacao.preencherComobox(listaBanco, contajComboBox);
            }
            if (listaPlano != null) {
                planoContasjComboBox = Formatacao.preencherComobox(listaPlano, planoContasjComboBox);
            }
        }
    }

    @Override
    public void setCliente(Cliente cliente) {
        if (cliente!=null){
            this.cliente = cliente;
            unidadejTextField.setText(cliente.getNomeFantasia());
            carregarComboBox();
        }
    }

    @Override
    public void exportarExcel(String caminho, String nomeArquivo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void inicializarCliente() {
        if (usuarioLogadoBean.getUsuario().getCliente() > 0) {
            this.cliente = Formatacao.consultarCliente(usuarioLogadoBean);
            if (cliente != null) {
                unidadejTextField.setText(cliente.getNomeFantasia());
                selecionarjButton.setEnabled(false);
            }
        }
    }
    
}
