/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmLocalizarArquivo.java
 *
 * Created on 15/03/2011, 11:47:17
 */

package tela;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Contaspagar;
import tela.ContasPagar.IContasPagar;
import tela.ContasReceber.IContasReceber;
import tela.OutrosLancamentos.ItelaMovimentoBanco;
import tela.Vendas.IVendas;


/**
 *
 * @author wolverine
 */
public class FrmSalvarAquivo extends javax.swing.JFrame {
    
    private  Contaspagar conta;
    private File file;
    private IContasPagar telaContasPagar;
    private ItelaMovimentoBanco telaBanco;
    private IVendas telaVendas;
    private IContasReceber telaContasReceber;
    private int numero;
  
    /** Creates new form FrmLocalizarArquivo */
    public FrmSalvarAquivo(Contaspagar conta, int numero) {
        this.conta = conta;
        this.numero=numero;
        initComponents();
        URL url = this.getClass().getResource("/imagens/logoRelatorio/iconetela.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        String localIni = System.getProperty("user.dir");
        File novo = null;
        if (numero==1){
            novo = new File(localIni + "\\" + conta.getNomeArquivo());
        }else if (numero==2){
            novo = new File(localIni + "\\" + conta.getNomeArquivo02());
        }
        carregarjFileChooser.setFileFilter(null);
        carregarjFileChooser.setSelectedFile(novo);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public FrmSalvarAquivo(IContasPagar telaContasPagar) {
        this.telaContasPagar = telaContasPagar;
        initComponents();
        carregarjFileChooser.setFileFilter(null);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public FrmSalvarAquivo(ItelaMovimentoBanco telaBanco) {
        this.telaBanco = telaBanco;
        initComponents();
        carregarjFileChooser.setFileFilter(null);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public FrmSalvarAquivo(IVendas telaVendas) {
        this.telaVendas = telaVendas;
        initComponents();
        carregarjFileChooser.setFileFilter(null);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    public FrmSalvarAquivo(IContasReceber telaContasReceber) {
        this.telaContasReceber = telaContasReceber;
        initComponents();
        carregarjFileChooser.setFileFilter(null);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }
    
    
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        carregarjFileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salvar Arquivo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        carregarjFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        carregarjFileChooser.setCurrentDirectory(null);
        carregarjFileChooser.setDialogTitle("Salvar Arquivo");
        carregarjFileChooser.setSelectedFile(new java.io.File("C:\\Program Files\\NetBeans 7.4\\teste"));
        carregarjFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarjFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carregarjFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(carregarjFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarjFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarjFileChooserActionPerformed
        file = carregarjFileChooser.getSelectedFile();
        if (file != null) {
            if (conta != null) {
                FileOutputStream in = null;
                try {
                    in = new FileOutputStream(file);
                    if (numero==1){
                        in.write(conta.getArquivo());
                    }else if (numero==2){
                        in.write(conta.getArquivo02());
                    }
                    in.close();
                } catch (Exception ex) {
                    Logger.getLogger(FrmSalvarAquivo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else {
                String nomeArquivo = file.getName();
                String caminho = file.getAbsolutePath();
                if (telaContasPagar!=null){
                    telaContasPagar.exportarExcel(file.getPath() + ".xls", nomeArquivo + ".xls");
                }else if (telaBanco!=null){
                    telaBanco.exportarExcel(file.getPath() + ".xls", nomeArquivo + ".xls");
                }else if (telaVendas!=null){
                    telaVendas.exportarExcel(file.getPath() + ".xls", nomeArquivo + ".xls");
                }else if (telaContasReceber!=null){
                    telaContasReceber.exportarExcel(file.getPath() + ".xls", nomeArquivo + ".xls");
                }
            }
            this.dispose();
        }
    }//GEN-LAST:event_carregarjFileChooserActionPerformed

    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser carregarjFileChooser;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
